### ISSUE TITLE
is it possible to implement this with custom MQTT Server?

### ISSUE THREAD

**Issue by RezaSaadat1** [heisenware/vrpc-js#54]
I saw this this library useful for my project. i checked out the examples and didn't see any mqtt configuration on the client side,
i'm wondering is it possible to utilize this library to on-prem server and with custom mqtt config, or is it licensed or something?

**Comment by bheisen** [comment]
Hi @RezaSaadat1!
Yes, you can use your own broker. See the documentation [here](https://github.com/heisenware/vrpc-js/blob/master/docs/api.md#new_VrpcClient_new) for the client side. I hope that answers your question.
Hint: Make sure to use the same *domain* on agent and client to get the communication done.
