### ISSUE TITLE
Add possibility to set a custom MQTT client Id in VrpcAgent

### ISSUE THREAD

**Issue by cstim** [heisenware/vrpc-js#56]
**Is your feature request related to a problem? Please describe.**
When the VrpcAgent object starts the MQTT connection, it also sets a MQTT client ID. This client ID is generated in the VrpcAgent.js code but cannot be set from the application code. Sometimes the application needs to set the MQTT client ID into some controlled string before the MQTT connection is established, so it should be possible to set this.

**Describe the solution you'd like**
Add an optional `mqttClientId` argument to VrpcAgent.serve(), or as option into the constructor.

Related: In `VrpcClient` there also isn't an argument or option, but the mqtt client id is set in the constructor as member variable `this._mqttClientId` already, so the application code can just modify that member variable before calling `connect`. Not particularly elegant, but works already.

**Comment by bheisen** [comment]
Yes, I believe that you are right. I will add the corresponding option, both for the agent and the client.

**Comment by bheisen** [comment]
I think I like the option in the constructor better and keep the `serve()` function free from any configuration. Will hence proved an own PR soonish. Thank you for your PR anyways!
