### ISSUE TITLE
Missing error handling of failed MQTT subscribes

### ISSUE THREAD

**Issue by cstim** [heisenware/vrpc-js#58]
**Describe the Bug**
The callback on the mqttClient.subscribe() call receives an argument `granted`. This array must be checked for each topic's `qos` value, because this might be value 128 saying that this topic subscribe has failed (Reference: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718071  SUBACK packet payload format, “Allowed return code: 0x80 Failure”). This must be checked for explicitly, but currently isn’t done.

**Steps To Reproduce**

1. Set up a broker that does topic-specific permission checks
2. Set up a username/password to be used for the vrpc client that is allowed to log into the broker, but does not have topic permission on the topics needed for vrpc
3. Run the vrpc agent and/or client. Observe that it doesn't print any error. Upon trying to access any of the VrpcAgent's classes, one just gets the infamous `Function call "...()" timed out (> 6000 ms)`

**Expected Behavior**
If the MQTT subscription fails, there must be a clear error event from the VrpcAgent and VrpcClient objects so that the application code can decide what to do, such as restarting the whole Vrpc connection or such.

**Comment by bheisen** [comment]
Thank you @cstim !

I am fine with the suggested behavior and the code-content of the PR! Before merging, please see my minor comment there.
